import { AnimalSpecies, TimeOfDay, WeatherType } from '../types';

export interface AnimalConfig {
  species: AnimalSpecies;
  emoji: string;
  name: string;
  size: number;
  speed: number; // pixels per second
  preferredZone: 'ground' | 'water' | 'air' | 'tree';
  activeAt: TimeOfDay[];
  avoidWeather: WeatherType[];
  maxCount: number;
  spawnChance: number; // 0–1
}

export const ANIMAL_CONFIGS: Record<AnimalSpecies, AnimalConfig> = {
  deer: {
    species: 'deer',
    emoji: '🦌',
    name: 'Geyik',
    size: 60,
    speed: 25,
    preferredZone: 'ground',
    activeAt: ['dawn', 'morning', 'golden_hour', 'dusk'],
    avoidWeather: [],
    maxCount: 3,
    spawnChance: 0.7,
  },
  fox: {
    species: 'fox',
    emoji: '🦊',
    name: 'Tilki',
    size: 40,
    speed: 35,
    preferredZone: 'ground',
    activeAt: ['dawn', 'dusk', 'night', 'midnight'],
    avoidWeather: ['snowy'],
    maxCount: 2,
    spawnChance: 0.5,
  },
  rabbit: {
    species: 'rabbit',
    emoji: '🐇',
    name: 'Tavşan',
    size: 28,
    speed: 45,
    preferredZone: 'ground',
    activeAt: ['morning', 'afternoon', 'golden_hour'],
    avoidWeather: ['rainy'],
    maxCount: 5,
    spawnChance: 0.8,
  },
  squirrel: {
    species: 'squirrel',
    emoji: '🐿️',
    name: 'Sincap',
    size: 24,
    speed: 50,
    preferredZone: 'tree',
    activeAt: ['morning', 'afternoon'],
    avoidWeather: ['snowy', 'rainy'],
    maxCount: 4,
    spawnChance: 0.75,
  },
  owl: {
    species: 'owl',
    emoji: '🦉',
    name: 'Baykuş',
    size: 35,
    speed: 0,
    preferredZone: 'tree',
    activeAt: ['dusk', 'night', 'midnight'],
    avoidWeather: ['rainy'],
    maxCount: 2,
    spawnChance: 0.6,
  },
  duck: {
    species: 'duck',
    emoji: '🦆',
    name: 'Ördek',
    size: 28,
    speed: 20,
    preferredZone: 'water',
    activeAt: ['morning', 'afternoon', 'golden_hour'],
    avoidWeather: [],
    maxCount: 4,
    spawnChance: 0.8,
  },
  swan: {
    species: 'swan',
    emoji: '🦢',
    name: 'Kuğu',
    size: 45,
    speed: 15,
    preferredZone: 'water',
    activeAt: ['morning', 'afternoon', 'golden_hour'],
    avoidWeather: [],
    maxCount: 2,
    spawnChance: 0.4,
  },
  hedgehog: {
    species: 'hedgehog',
    emoji: '🦔',
    name: 'Kirpi',
    size: 22,
    speed: 18,
    preferredZone: 'ground',
    activeAt: ['dusk', 'night'],
    avoidWeather: ['snowy', 'rainy'],
    maxCount: 2,
    spawnChance: 0.45,
  },
  frog: {
    species: 'frog',
    emoji: '🐸',
    name: 'Kurbağa',
    size: 18,
    speed: 30,
    preferredZone: 'water',
    activeAt: ['morning', 'afternoon', 'dusk'],
    avoidWeather: ['snowy'],
    maxCount: 6,
    spawnChance: 0.7,
  },
  koi: {
    species: 'koi',
    emoji: '🐟',
    name: 'Koi Balığı',
    size: 30,
    speed: 20,
    preferredZone: 'water',
    activeAt: ['dawn', 'morning', 'afternoon', 'golden_hour', 'dusk', 'night', 'midnight'],
    avoidWeather: [],
    maxCount: 6,
    spawnChance: 0.9,
  },
  butterfly: {
    species: 'butterfly',
    emoji: '🦋',
    name: 'Kelebek',
    size: 20,
    speed: 40,
    preferredZone: 'air',
    activeAt: ['morning', 'afternoon', 'golden_hour'],
    avoidWeather: ['rainy', 'snowy', 'foggy'],
    maxCount: 8,
    spawnChance: 0.85,
  },
};
